#!/bin/bash
array=()
FILES=../log/*
flag=0
for f in $FILES
do
    echo "Processing $f file..."
    # take action on each file. $f store current file name
    while IFS=' ' read -ra line || [[ -n "$line" ]]; do
        #echo "line read from file: ${line[@]}"
        for ((i=0; i <= ${#line[@]} - 1; i++))
        do
            #echo "${line[$i]}"
            if [ "${line[$i]}" = "search" ]; then
                if [ $flag -eq 0 ]; then
                    flag=1
                    #echo "------adding ${line[$i+2]}"
                    array+=(${line[$i+2]})
                else
                    for ((j=0; j < ${#array[@]} ; j++))
                    do 
                        if [ ${line[$i+2]} = ${array[$j]} ]; then
                            break
                        elif [ $(($j+1)) -ge ${#array[@]} ]; then
                            #echo "------adding ${line[$i+2]}"
                            array+=(${line[$i+2]})
                        fi
                    done
                fi
            fi
        done
    done < "$f"
done

echo "Total number of keywords searched: ${#array[@]}"